name: reproduire-sur-stackblitz
on:
    issues:
        types:
            opened

permissions:
    issues: write

jobs:
    reproduire-sur-stackblitz:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5
            - uses: huang-julien/reproduire-sur-stackblitz@edd77eee0ffdae795c9dfd4e5b3b745740672439
