name: reproduire-sur-stackblitz
on:
    issues:
        types:
            opened

permissions:
    issues: write

jobs:
    reproduire-sur-stackblitz:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
            - uses: huang-julien/reproduire-sur-stackblitz@edd77eee0ffdae795c9dfd4e5b3b745740672439
